apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

namespace: metallb-system
generators:
  - metallb-helm.yml

resources:
  - namespace.yml
