apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr
  namespace: media-sonarr
spec:
  secretName: sonarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sonarr.nebulanet.xyz
  dnsNames:
    - sonarr.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
