apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media
  namespace: media-sonarr
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeSource: Retain
  storageClassName: smb-sonarr-media
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.0
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: hl15.nebulanet.xyz/Media#sonarr-media
    volumeAttributes:
      source: //hl15.nebulanet.xyz/Media
    nodeStageSecretRef:
      name: media-smb-creds
      namespace: media-sonarr
