apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
  namespace: media-sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb-sonarr-media
  volumeName: nas-media-sonarr
