apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
  namespace: media-sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb-downloads
  volumeName: nas-downloads-sonarr
