apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - traefik-dashboard-users-sealed.yml
  - dashboard-certificate.yml
  - dashboard-middleware.yml
  - dashboard-ingress.yml

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: traefik
      homelab.izzard.me/cluster: core
      homelab.izzard.me/environment: production
      homelab.izzard.me/upstream-source: helm