apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dashboard-certificate.yml
  - dashboard-ingress.yml
  - dashboard-middleware.yml
  - dashboard-users.yml

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: longhorn
      homelab.izzard.me/cluster: core
      homelab.izzard.me/environment: production
      homelab.izzard.me/upstream-source: helm