apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      initContainers:
        - name: gluetun
          image: docker.io/qmcgaw/gluetun:latest
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - secretRef:
                name: pia-creds
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: sabnzbd
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: downloads
          persistentVolumeClaim:
            claimName: sabnzbd-downloads
