---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: downloads-smb-creds
  namespace: media-sabnzbd
spec:
  encryptedData:
    password: AgCQ9Oyp+2RCt5CJmY/ia33vLdshsiQSYRZs3eA5oJLDp3MG+GNBD8JXTZavRgnWv8zajIi1pX++TLajb59jDsmN55hAa27uxNFwTWEwvO8NE3UZ7DSjLVAoYkUvCXj2OzZ4aOae8IScon90j8rl2errU/fsB9qjeloZbCJ5ub+1b+6K8dx0s7n9HEdNCL5wOgNm39XnJPzN6VMZHTzi1MBwcHPVmoXeV0g5yrioG0ZsDy+ovFSPF+YqN888xqlQbYmpQNjKdOaGAYes4otNel8hykwfUuRqSrcXd5QqKTSXnv8U6HlMQfHZ6lrCTRUXlKthQ8WECGyWMyyV25P53TVvey3LoTVF6eTPoUUOtSK1pu7nYLS5BtGqlWn203C9btj6iPEAK/wWxUGu55dt/8CZcDYTYPYI0hcZ0MXc4LCFlUB3u2yAa6KDFu1VEZ3BEslFXPt2CBUJOUZfxltE+x2/bPLpYkih0qjxv8iUXB/h9Vo9NFwarQ84Go9ZMrfFp9+Db1BuLh5g3blVG+4uPhfmoLqjELAjun0ZxwXp8KAixnweFK+HeZr33egBxeV+xKJG03gaXBmk3SsI1hkhBIaKajOs+rWCsPtODA3F4MHOLwf47sWscj0+KYmPSgIlIVmMsgeb5/n/DMgYJz9s7vJSoAKCqbv7Eje6ZhwFsxLXgMqd0JUbbSZ0cfPPiL9DcTpT60d0LM4v+dP1BqKXW+0jvyUtcLu2PU+gG9utVeo=
    username: AgCKMgA7i1Hp4hAvCI27/zZ1zhpOYXBk0EgC40S/IWdwG9Vdf4eXxEYgmcbchztgvvahkFzZSLV9caFL0FGoG3VJGvlbumLiYDYfJ0bA1HiE7pTKnM9LA9qgduhUFJ+BqvJiPAcqaOJb4q1tBMVIs7a68pToolhDlzvOY/x7w0/04SzdqicyPif+ilbFpMZPkPZntH3hLbk3chcFpYtIBHrHSpA0tSGWnp9AYW/Ncj3mCKQoH+ubQ19Z3+Ox+wg0vxLAdgUwcXFTj63zjHWxHdt0q1w06L+HGRbsAyuXqHWs2U4P9rNLfJVE8ArUw4LRnx5lsRP2hG0HYDnBkXo9SilGb57rD754Wpai8dbxK1VFGuiPUQCB3QntBayDYaEPmCKYaGDxyeNqQQ0kyrFSUYXH6wAhWVWx1MMAuYoBlg/5tKuzG8Wtbg6Efc3ywQP5dVbJHj9lo0ZAY7oYm/ZYPnXWL5yEsiRm4C6nu8RVxxstQYb05RJoXPFi1XP0QV1ltcUOHcGFc3IvD7hQPBJI9TdIhb3qwsX3SLeZyxnh1kQ6RIrXMt2uT7VNz1vTbus7jn5iZXa02Oit7ir23fMCOlGiD64N/FnG18CVLN9rrG/h7Qtk5YA15kGWQ/O5ohwOCaBxpx3S8cMOfSQdAG5d9rnYE4HMxsOdJIaxQgru2rZpR4DV2bgtSYY0d812NB809IkKtZAgOoNb
  template:
    metadata:
      creationTimestamp: null
      name: downloads-smb-creds
      namespace: media-sabnzbd
    type: Opaque
