---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: downloads-smb-creds
  namespace: media-sabnzbd
spec:
  encryptedData:
    password: AgCsOo6WU5FPds1k9zo4F1v5Hhzx4s5JyG77iv4fgcoWdXk8uN4DerfJSzua0TZFVaEPwyIIKFyG2u6pG1YSftt/nkF+h4M+Hbi0XfnlKh69pqQ2C5ZKU6038bqnctpC2aKeQBjJdyzR45CfRg4GSsWmZQYVPlG0xJkkGYC37ESzN6wyPBz6eGc1QBcjwYlU/AK685ODUyMhF7TQxW56Vi+EW8i1tyvZCIWAVqe6jf+04S5dbGcoewtFk6VkaprlVW6a4Ahg+8qi2jtNvbkhZ7L+VMOG9oBPy85bQ0p3nZEfS5Z5rG/JT0qQv0gJwq2x39bUFK+ws1o23Iqk2QKp/l9amlqg6ZbnplgUTFZ0wJBVXwNeol+fGdYbaElug288QROH9FbYjswHZcs7LSBKBQsUOdCNo5ZkxgyQ1EXZvwvs5rUZTDlHRxdvfXQfiE2ppn0rXPGNeLLHioZuuRzmkGmcd0IWW6hJP3rgApDSLFqnlhSC8ygvQ2ohPCM6ntbk5rmstUHpLzcwRO3qd+o7dM4YShrUZBvPXlhJ4k6V+UyVe1quWkNKcDsNayqV2OqIcGbOLs3FlaGuAIIcTRjMDapYhhdOOkMPZe4fycQTUPHb6Uz9PftWhpCOU4mrqjMZLhNOiNEv7/pngZjQkE0NKZ4cpF50YV+S5Dvpfl5Qz9nDvuyuw7CCohvVCvVaUUgMTyg0yxZkYrWFVKjZnr2rrmakga29wes16vsKM8+Bnkg=
    username: AgCa0wpyrhb2xsFiI4clK8/S9n54ZasvSLoIfUudjhb71/NZeuo9AGTai0Z45PcAVO+nrXZ0+kMrnsUdy+wP3Cdhml/NB2kGwJZL2OaHrhEL1n7nIZJuoRAnow95vbtkdYmrNiGzAE8HefL6u27yI19/jIkkAd4r58X1flezqIEKlkIgLRlrTx9HW47Oz4x15Jfdd6F9HZ9jfdt8B3q/8LNxA76XQYKnRLPoD+4IbKmpm4X96qybV6+ZtHkADgIH4wP6S7mGkrWylFfhRe9PBidKmrsYQj9NCVI1aNbWjhyD98s37X6X99InJbAxfFVIAj+KXN7fTC+DO+Ol9hR8RQqroBSNpcR0uOYIOUuBlWrGQgAD7HBkVDHmXCj+YUXVio61ecB81czRSNE5qx9yg2EOYseVf2VUWlnTvgE1XLHqbToQogM1GRwE8D0LREU2m8neeqaHJ8qKVNZ93Kl5lEh75MQZAiQ9K74UyjLOyEqGtY0p1nwX9MJqN80ZILq0dVEDyy0rbHTk0tGw/yA2/zHFOSl4qCUTW+ArfzrRmfI0s1e1R2P91DfvNakCDrTXVv+Fo3RbMDDA5dTKF2HWtIeYKsi0unPoLNxM7TWcVxctYcP3JZ7tHnXW0F2VgvdEuwnR0FwJR7t3M6BLCz33rpXlW1nC0N+KMGZYu4L5CoEOHks6MUOjqpAmfjuz6bHjxb1ZJuCsIoBE
  template:
    metadata:
      creationTimestamp: null
      name: downloads-smb-creds
      namespace: media-sabnzbd
    type: Opaque
