apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: powerdns-admin
  namespace: dns
spec:
  secretName: powerdns-admin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dns.nebulanet.xyz
  dnsNames:
    - dns.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
