---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: powerdns-admin-env
  namespace: dns
spec:
  encryptedData:
    SECRET_KEY: AgAh5peVc0YGQWPVJFuw7nTBGfU43IWB4kmbfM7L9vYqpEy7+O43cfdwwdv2veXHOLPyOgU2ZptdVhLIYdPHlCbRLtk6RrF6WWZfCXTtwZ8kr5jTOjmU2mcmo+7O0q62n88NLmqml8u5Z++0Ze3uwEjRVIIEJogYZaoYpdUJ0xspuFEnW75ptHo8hfudjf9smBh4ft6GllxhkM8pOeqz+lM74F7weNsc9X/PldRkU+w4hGNVQ+zRaNt7dTWFbD58TMbcbHGElvIKpUi29ViR3WA1BrH9XILiG0XUEAxS2b42Y3AxMEHl+V9oQI8F5JVDkbbMaqftSOOXON7GYeRYJswhPixKQyHKXG4cXPxNGRZRIXUguamzdOsMsNp1K96T21+avV4Mo+/Qg9QX7kVyRXzRoSun/5kuFcHpWpkVtaz+ivhKKK0ydF2LPBYEi9TM1wEtrrGP1WNsGM7ig5eGHQwXnbJMGHMW3LL3gV0i6j15bCLIrI5Wg7EMIWd0psDMauViC+vhjKHc95xHGiHqton5EQ0xbqrumF0XF4q7yEibi973pDqaA0GRnBGGa6fg1qE9mKkF9/fued9vJFY9i+BnyjFGIBQIkUHA4zOntd/BcdY6CegKr2IPYrowBavTbZrqNrFQF3w/cSZcrZhZuKY/SUb6W3zDn9cj5xuUQ4SctXiIs1Kj58OtTB1JxM3yfDYWsRcahOrLnZF+N1wz2BmovZ9KAQlEPknRz0TbgUSBiFxkWgBOv/1/pplb+dNW6Oyk8Dz0rtUc2Ozl5zhMU5Mh
    SQLALCHEMY_DATABASE_URI: AgBnS4cau1iSN8fdaK90EWbwUsaYLyXByyY1trZHpAI7+KBeiUq85fVFN9XCOo1q7uoHFHCsllVQNazb4WSC8f98F817SOqDTQ2iMeWsvnnzfGNahX9OC+B4JRClw9JjSfgQNPYi1xVJHTbC5WeRCNXR7moizrhFudzHrfkCgEmc8gvzf9RbB8AD3M70vc9CVFGA/BWrXU8xlYKnwLIr6AAmAGD/ei5lwUx0td/3lPf6DsUgqPI+vdT6Hj5sZd1wdGFv65MNI74sf6zahXY9UmPo3SudQUhf96rRd5kgu68CDsE6C/9Swn8rovmUSZUkRG//EIQloP0hKXTjmANDcwGW7b5g5CTmG4cHebaglRu74D97LCuAZTp6X6zI+NanCH8Z7tKScVT04Wj/uXNrk3anIfL+5TT0fJHYR726431iWILwMgwakOtlRdBQ09YgYI6emYwzYI7Ez8TxrV4XX6IVSW0NbPMTGSGkBU+0/aLHcZRu+h1+My0P8r08hA93cXTD5i5AyGmWoTJaW5rIROccbQkZGYnFgTF1BtDSXMei2sbBn3dbQcu1a8dZOKjZoU/SuIFS9bRTRFGCVBcy+xv3pLrtpgo3/hd/iJLgiJ4b3a3mwwSRdXcULfZvVfsuc0GJnCv+VzZRDEB5kB4x0I8oudKkE5MI1q2JtiRK4v0f8czW738E5dMCN6yo+xVs4RyrPyRsOCi//SGV49y5b9bzhb78BvblUL3ukIU6eD4r3o3liKd+SlH0n256DwEmhd7tMSWWYxcW6mDD1C/3l2t7O0bVD3kgCE2+2WxSdb4A/KOIFAU=
  template:
    metadata:
      creationTimestamp: null
      name: powerdns-admin-env
      namespace: dns
    type: Opaque
