---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: powerdns-admin-env
  namespace: dns
spec:
  encryptedData:
    SECRET_KEY: AgAEpd65WXj5xEL+PrMrclnqDwVZ2JYPqImGlHZmDa10rPyLuvAkZ8KBSSZX0t0+LWuCjN6U2/UQBOm2MlUHOcKTn7nFL/MV1kneMsbqDSdykn3Z6sjyJwkXZ6QZJK6lsu5YQm9+hkx1DCKE71fzYBJ1mtWAiFN8vMEtGycOb3l5crfT5b2PM6f5gvZUaWZBDyepFGBV3l6hQK2XiAPvBOGhIcxZegWK6fsJrzDOUev6y/e4H73C0idsTE5OSxSr86OD0I1pSs7f1YYlKZk9qIABuD2u8WMhD3RIyAb6zLE7cT3JEAT5CiemU5G4wfcQEewU6VopNvxKRh7kiDHTeME+RmajRPSO0PloC+6tZdbNuTfy2K9otfGL5yz52axYOE8sfFQy8n94hq0y4vci15qLrMBSB+FvQPpNcffTRUN7uun80Lp1v5qu8Gzjqu53HzQOFioJinQxu3YrCeadrO8dJh4RfY4EAbz+mrL0Pwc2Co+V3lAa/ok70u6jPFSL1WjjIgnlMx4KJgqvaaE9Fn25Ilm+0s0TsDL+4Rt/NJ4eeloTM9WVzBMLrxHDmUkLRzSH4EXsjz2Dp4ipryWl+I+nlJGgErxjBZUFejft7wv/JMVCXt2/CAUgoOSR4MFgT9NzNklFUZYmrlaLHpqeLkLaf5P1ZY9OFuYexlhG8hIv9sX9oLyWYFQDX4uCSMpMNPoOPT1xuk3lTfwkm4onAPtzOqt4wldjjNf3XC5SrgQSF4gqncrLfaNAKOtRqNM8vJGULzoKCkpPHCfmfoIStwXg
    SQLALCHEMY_DATABASE_URI: AgCUJ99rmYXZLDrKjSI3ZxP/COIA7JrSCDNtfvHFW+w0lQw2xyJKP0xy5wvBXstKUIviyoja2PjQrY5YSX9496ZHcT4jH6ejWS6ctwwi30cMIGrz0jOZ0BlBo5eyAhP36WcwY+hJGD8GAYCJYKTvTxAqJKlC9CnLfAL2Yb8rjuFO7Ood3PtDx0OS58kpplqVknEt/hhxxxZ516WUaNngxOkqrJbVAe/PZ9Yzs491s4cAVmxCGpgrhOev0FGs5/Rgxv8rnOYWAcTVhA29FVVb23cyvR/D2bbvvOc4mliYwSftLbi9O9U0SMrVrmS+UqYemceMGW4VFjS0we73PmRvtepbp6sr5PVsRSwTTfvEKmQ2FqDbmyZcpgzDXT8Ro9jBeU1oyjvOuXUWNqkyabwTxzfVEFPbWjg0TObbWcuQ9z4DyLe3sfNgGaAXka9Sy+XrLHjtDWCGsIP9ufwPDl9VbD3ic2G1m0bcz4abLg7wIrRlLa1+JZUucgmlJpoGJbB78FnxSQh9cyRQWqNj9NT/3VscwQ12WolMjuNjX+PpfUE7tXs76uMIy3L7AFTSgVLAezVVF5Wn2aO85VZLEHXb2mimSMNx5ZJTrAGvViFTixjBLe3Sm8M/GBnJqNAjabThn+VUgwImvhsv+MYeiNm6YRdKrwVBFcmclxFVwDLAY1pq+XEr9Z6bHE4NWW/3Mg+w0VGw9yhEC976qutMP+iP4d54vFGvU/zxyrNXjwzJMXdn4wAdMVgFK093WRgK8eQ4Ou3EZFtFVYaBS7OdijkrJ1MCrMiYvU5sKuWfc1Qg4FbjmzkBCko=
  template:
    metadata:
      creationTimestamp: null
      name: powerdns-admin-env
      namespace: dns
    type: Opaque
