apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

namespace: cert-manager
generators:
  - cert-manager-helm.yml

resources:
  - cloudflare-api.yml
  - lets-encrypt-staging.yml
  - lets-encrypt-prod.yml
