apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  app.kubernetes.io/managed-by: argocd


namespace: cert-manager
generators:
  - cert-manager-helm.yml

resources:
  - lets-encrypt-staging.yml
  - lets-encrypt-prod.yml
