# Ensure we are using public DNS Servers for DNS01 Challenges
dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53,8.8.4.4:53,9.9.9.9:53"
dns01RecursiveNameserversOnly: true

crds:
  enabled: true

global:
  leaderElection:
    namespace: cert-manager