apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-tautulli

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

resources:
  - resources/namespace.yml
  - resources/pvc-tautulli-config.yml
  - resources/deployment-tautulli.yml
  - resources/service-tautulli.yml
  - resources/ingress-tautulli.yml
  - resources/certificate-tautulli.yml

