apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate-dashboard.yml
  - ingress-dashboard.yml
  - middleware-dashboard-auth.yml
  - sealed-dashboard-users.yml

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: longhorn
      homelab.izzard.me/cluster: nebula
      homelab.izzard.me/environment: production
      homelab.izzard.me/upstream-source: helm