apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-prowlarr

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

resources:
  - resources/namespace.yml
  - resources/certificate-prowlarr.yml
  - resources/deployment-prowlarr.yml
  - resources/service-prowlarr.yml
  - resources/ingress-prowlarr.yml
  - resources/pvc-config.yml

