apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: authentik
  annotations:
    metallb.universe.tf/allow-shared-ip: "core-services"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.14
  externalTrafficPolicy: Cluster
  ports:
    - name: ldap
      port: 389
      targetPort: 3389
    - name: ldaps
      port: 636
      targetPort: 6636
  selector:
    app: authentik-outpost