apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-plex

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

resources:
  - resources/namespace.yml
  - resources/pv-media.yml
  - resources/pvc-media.yml
  - resources/sealed-media-smb-creds.yml

