apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-plex

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

resources:
  - resources/namespace.yml
  - resources/sc-smb-plex-media.yml
  - resources/pv-media.yml
  - resources/pvc-media.yml
  - resources/sealed-media-smb-creds.yml
  - resources/pvc-plex-config.yml
  - resources/sealed-plex-env.yml
  - resources/deployment-plex.yml
  - resources/service-plex.yml
  - resources/service-plex-extras.yml
  - resources/ingress-plex.yml
  - resources/certificate-plex.yml

