apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: pgql-creds
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgql-data
      volumes:
        - name: pgql-data
          persistentVolumeClaim:
            claimName: pgql-data
