apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

namespace: authentik
generators:
  - authentik-helm.yml

resources:
  - resources/shared
  - resources/database
  - resources/redis
  - resources/authentik
