apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebula-cluster-metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb-nebula
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/managed-by: argocd
    homelab.izzard.me/cluster: nebula
  annotations:
    homelab.izzard.me/environment: production
    homelab.izzard.me/upstream-source: helm
spec:
  source:
    repoURL: https://gitlab.com/joeizzard/homelab.git
    targetRevision: HEAD
    path: services/cluster-services/metallb/overlays/nebula
  destination:
    name: nebula-prod
    namespace: metallb-system
  project: nebula-cluster-services
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
