apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebula-cluster-smb-driver 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: csi-driver-smb
    app.kubernetes.io/instance: csi-driver-smb-nebula
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/managed-by: argocd
    homelab.izzard.me/cluster: nebula
  annotations:
    homelab.izzard.me/environment: production
    homelab.izzard.me/upstream-source: helm
spec:
  source:
    repoURL: https://gitlab.com/joeizzard/homelab.git
    targetRevision: HEAD
    path: services/cluster-services/smb/overlays/nebula
  destination:
    name: nebula-prod
    namespace: kube-system
  project: nebula-cluster-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
