apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.nebulanet.xyz
  dnsNames:
    - auth.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
