apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: sealed-secrets
      homelab.izzard.me/cluster: core
      homelab.izzard.me/environment: production
      homelab.izzard.me/upstream-source: helm
      