apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-radarr

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

resources:
  - resources/namespace.yml
  - resources/certificate-radarr.yml
  - resources/deployment-radarr.yml
  - resources/service-radarr.yml
  - resources/ingress-radarr.yml
  - resources/pv-media.yml
  - resources/pvc-media.yml
  - resources/sc-smb-radarr-media.yml
  - resources/pv-downloads.yml
  - resources/pvc-downloads.yml
  - resources/sc-smb-downloads.yml
  - resources/sealed-downloads-smb-creds.yml
  - resources/pvc-radarr-config.yml
  

