apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr
  namespace: media-prowlarr
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: prowlarr.nebulanet.xyz
  dnsNames:
    - prowlarr.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
