apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex
  namespace: media-plex
spec:
  secretName: plex-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: plex.nebulanet.xyz
  dnsNames:
    - plex.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
