apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: media-plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
  volumeName: nas-media
