apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-plex-media
provisioner: smb.csi.k8s.io
parameters:
  source: //hl15.nebulanet.xyz/Media
  csi.storage.k8s.io/provisioner-secret-name: media-smb-creds
  csi.storage.k8s.io/provisioner-secret-namespace: media-plex
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - noserverino 