apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-dashboard
  namespace: argocd
spec:
  secretName: argocd-dashboard-tls
  renewBefore: 240h
  duration: 2160h
  commonName: argocd.nebulanet.xyz
  dnsNames:
    - argocd.nebulanet.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    