apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors:
    pairs:
      app.kubernetes.io/managed-by: argocd

namespace: traefik
generators:
  - traefik-crd-helm.yml
  - traefik-helm.yml

