ingressRoute:
  dashboard:
    enabled: false

serversTransport:
  insecureSkipVerify: false

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true