apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr
  namespace: media-radarr
spec:
  secretName: radarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: radarr.nebulanet.xyz
  dnsNames:
    - radarr.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
