apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-downloads-radarr
  namespace: media-radarr
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeSource: Retain
  storageClassName: smb-downloads-radarr
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.0
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: hl15.nebulanet.xyz/Downloads#radarr-downloads
    volumeAttributes:
      source: //hl15.nebulanet.xyz/Downloads
    nodeStageSecretRef:
      name: downloads-smb-creds
      namespace: media-radarr
