apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media
  namespace: media-radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb-radarr-media
  volumeName: nas-media-radarr
