---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: downloads-smb-creds
  namespace: media-radarr
spec:
  encryptedData:
    password: AgBBxdDlI0CQ1ZIpuk5xXMYXbDmhlF+GbfLjypkpB/wnm7c5myAZrUL8hOzGXr0HwUfnOa8tQO4kCrO8V8KHTDB68xRwfvxwzpNR26AwNyEHrihgGxPbgOX+Y2djVQrxps2AogTlQagAl6AMYUf8EHJc+2J85wp9XnarT2K3AJwYmul01bLhzBOq3vZrH5ycLi8HXhYYkxiYTEYWTNgoONvyfIHN+oonJvThevAMEvyhZEE3OLwL8IbJvHPyQZGn9EJexJVt7yhOZngHrOyGdpAieybw0u4HsJLxDtSl1Gy6dOk8uG25m+w5WyB6QB4EvqRM59jjZFnOYSIx0HEA9S9kAUxR20051CN8byOYS3d9dRVvyUVR19nfsX+Ll/PeNqxbRB9u+OSJK0ivNA8iL71zSXszbegfExIsA7lass/s9Yx/qBSL3NSsFumyxttbf1gZaF0jN04HvsFTVeH44yyjC+DiOlRMhcZiBhZvfnjzrnLBnfXZf+xH5QP2wiFFNw9BRorf5TWpRuV8jfr6i7tfjuTU0buWEfACr2N6F+lukyN66Kx5IeO9jZ+HRRVHcD7m6eBHDAX+Qemia46LGlevTclR/QMe+lTL02qkr/UeINaNYWNBX5eWI/RDaING1L2KG1snfUK2k0ah3bgZGH2MVOOzVtKHzRS+Bi+8VBGQOVj8RaYWNqgMNSnFBvgydUC+Jf0luIR8M+uqo61zzHsUBrjxQRL280Ti4BHQPzo=
    username: AgBif/GgwET+fwqw1Xhw94/6OO8wLw1UvfnCVCk68JeDc1MchWNhBkAoKa1bgB6m/plPBuX+o8SZCI3J1c18+e3+vK/uoHDqeyc3Lwjy8WS7me+9w73T/CILpfBkPv+n5VHc9HdvkOUmir8FnWV86FvnrNCjyL0YFGjOij0zEm6Nil/MuKYxdPwNiqjPVtX9HMRxO3kJf3McDGwJPJokfaundjxzB7ZpV6RNq6m3P5Up1Jye+D8JcPkW36HjFohbrBk9P0IsmuyjBf4tJKNBYPIN3xcMxHGyAK7eke+OcFFDTocubK0NagrTSpuPliiXKMcTXw7BCQq3aw53Pgoas/fdGYlC2T5JEtCY3GVlTh7i5i8E2jJZ41TGyJiOZzddZ+DTtEUI+lHpcsKSNL3Dbbg6L9VnzNTSl99cUsqnfYKQnMb5nVlCFLgqX7ul3ofcHMO4bN0ggsPWwSkoc0P+5F0rxHLMSm8S8LYGdhBRYtF03wKRbfREs2PVcaj3E4yH9tVObNpBrhQ1mtiEhXB1R/fm5mPs1z3Bc2SUwvG44PlfrH3inis+Fr4JD0YfO2binPniD2Itis4ZNOWR/mo0R1XpcoE2IskRFJhaSC8Ig2Ty78OjaAQGKfYVh9YVn0plk3wisaVVABAKiq4C7LdtwWfa3k78v1nlT/ILE5qatqgutJIxc55/vVlagNxROlJSNnQ7QGpJc6AkUQ==
  template:
    metadata:
      creationTimestamp: null
      name: downloads-smb-creds
      namespace: media-radarr
    type: Opaque
