apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: powerdns-api
  namespace: dns
spec:
  secretName: powerdns-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: powerdns.nebulanet.xyz
  dnsNames:
    - powerdns.nebulanet.xyz
  renewBefore: 240h
  duration: 2160h
