apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns
  template:
    metadata:
      labels:
        app: powerdns
    spec:
      containers:
        - name: powerdns-auth
          image: pschiffe/pdns-pgsql:4.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5300
              name: dns-auth
            - containerPort: 8081
              name: api
          env:
            - name: PDNS_gpgsql_host
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_host

            - name: PDNS_gpgsql_port
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_port

            - name: PDNS_gpgsql_dbname
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_dbname

            - name: PDNS_gpgsql_user
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_user

            - name: PDNS_gpgsql_password
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_password

            - name: PDNS_gpgsql_dnssec
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_gpgsql_dnssec

            - name: PDNS_webserver
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_webserver

            - name: PDNS_webserver_address
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_webserver_address

            - name: PDNS_webserver_allow_from
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_webserver_allow_from

            - name: PDNS_webserver_port
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_webserver_port

            - name: PDNS_api
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_api

            - name: PDNS_api_key
              valueFrom:
                secretKeyRef:
                  name: powerdns-auth-env
                  key: PDNS_api_key

        - name: pdns-recursor
          image: powerdns/pdns-recursor-52:5.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              name: dns
          volumeMounts:
            - mountPath: /etc/powerdns/recursor.d
              name: pdns-recursor-config
            - mountPath: /etc/powerdns/forwardZones
              name: pdns-forward-zones

      volumes:
        - name: pdns-recursor-config
          secret:
            secretName: powerdns-recursor-config
        - name: pdns-forward-zones
          secret:
            secretName: powerdns-forward-zones
