apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: cert-manager
  homelab.izzard.me/cluster: core
  homelab.izzard.me/environment: production
  homelab.izzard.me/upstream-source: helm
  
  